# Generated by Django 2.0.13 on 2020-01-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200117_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
